/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.shibuya.ui;

import java.util.List;
import mx.itson.shibuya.entidades.Divisa;
import mx.itson.shibuya.negocio.Operacion;

/**
 *
 * @author shiri
 */
public class FrameConversion extends javax.swing.JDialog {

    /**
     * Creates new form FrameConversion
     */
    public FrameConversion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        cboDivisaUno.removeAllItems();
        cboDivisaDos.removeAllItems();
        
        cargarComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboDivisaUno = new javax.swing.JComboBox<>();
        cboDivisaDos = new javax.swing.JComboBox<>();
        txtPrecioDivisaUno = new javax.swing.JTextField();
        txtPrecioDivisaDos = new javax.swing.JTextField();
        lblPrecioDivisaUno = new javax.swing.JLabel();
        lblPrecioDivisaDos = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboDivisaUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDivisaDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtPrecioDivisaUno.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPrecioDivisaUnoInputMethodTextChanged(evt);
            }
        });
        txtPrecioDivisaUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioDivisaUnoKeyTyped(evt);
            }
        });

        txtPrecioDivisaDos.setEditable(false);

        lblPrecioDivisaDos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrecioDivisaDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioDivisaUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrecioDivisaDos)
                            .addComponent(txtPrecioDivisaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDivisaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDivisaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrecioDivisaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblPrecioDivisaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioDivisaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDivisaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioDivisaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDivisaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioDivisaUnoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPrecioDivisaUnoInputMethodTextChanged
        
        
        
    }//GEN-LAST:event_txtPrecioDivisaUnoInputMethodTextChanged

    private void txtPrecioDivisaUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioDivisaUnoKeyTyped
        
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57 || key == 46;
        
        if (!numeros){
            evt.consume();
        }
        
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.'){
            evt.consume();
        }
        
        if(evt.getKeyChar() == '.' && txtPrecioDivisaUno.getText().contains(".")){
            evt.consume();
        }
        
        if (txtPrecioDivisaUno.getText().trim().length() == 16) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtPrecioDivisaUnoKeyTyped

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        float valor;
        String divisaNomUno;
        String divisaNomDos;
        
        try{
            
                    divisaNomUno = cboDivisaUno.getSelectedItem().toString();
                    divisaNomDos = cboDivisaDos.getSelectedItem().toString();
                    valor = Float.parseFloat(txtPrecioDivisaUno.getText());

                    float precio = Operacion.obtenerPrecio(divisaNomUno, divisaNomDos, valor);

                    lblPrecioDivisaUno.setText(String.format("$%,1.2f", valor) + " " + divisaNomUno + " son:");
                    lblPrecioDivisaDos.setText(String.format("$%,1.2f", precio) + " " + divisaNomDos);
                    txtPrecioDivisaDos.setText(String.format("$%,1.2f", precio));
        
        }catch(Exception ex){

                System.err.println("Ocurrio un error: " + ex.getMessage());

            }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    public void cargarComboBox(){
        
        List<Divisa> div = Divisa.obtenerTodos();
        
        try{
            
            for(Divisa d : div){
            
                cboDivisaUno.addItem(d.getAbreviacion());
                cboDivisaDos.addItem(d.getAbreviacion());
            
            }
            
        }catch(Exception ex){
            
            System.err.println("Ocurrio un error: " + ex.getMessage());
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameConversion dialog = new FrameConversion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cboDivisaDos;
    private javax.swing.JComboBox<String> cboDivisaUno;
    private javax.swing.JLabel lblPrecioDivisaDos;
    private javax.swing.JLabel lblPrecioDivisaUno;
    private javax.swing.JTextField txtPrecioDivisaDos;
    private javax.swing.JTextField txtPrecioDivisaUno;
    // End of variables declaration//GEN-END:variables
}
